/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OriginalsRouteImport } from './routes/originals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PortfolioVfxCgiRouteImport } from './routes/portfolio_.vfx-cgi'
import { Route as PortfolioLiveActionRouteImport } from './routes/portfolio_.live-action'
import { Route as PortfolioAnimationRouteImport } from './routes/portfolio_.animation'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsRoute = OriginalsRouteImport.update({
  id: '/originals',
  path: '/originals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioVfxCgiRoute = PortfolioVfxCgiRouteImport.update({
  id: '/portfolio_/vfx-cgi',
  path: '/portfolio/vfx-cgi',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioLiveActionRoute = PortfolioLiveActionRouteImport.update({
  id: '/portfolio_/live-action',
  path: '/portfolio/live-action',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAnimationRoute = PortfolioAnimationRouteImport.update({
  id: '/portfolio_/animation',
  path: '/portfolio/animation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/originals': typeof OriginalsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/portfolio/animation': typeof PortfolioAnimationRoute
  '/portfolio/live-action': typeof PortfolioLiveActionRoute
  '/portfolio/vfx-cgi': typeof PortfolioVfxCgiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/originals': typeof OriginalsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/portfolio/animation': typeof PortfolioAnimationRoute
  '/portfolio/live-action': typeof PortfolioLiveActionRoute
  '/portfolio/vfx-cgi': typeof PortfolioVfxCgiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/originals': typeof OriginalsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/portfolio_/animation': typeof PortfolioAnimationRoute
  '/portfolio_/live-action': typeof PortfolioLiveActionRoute
  '/portfolio_/vfx-cgi': typeof PortfolioVfxCgiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/originals'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/portfolio/animation'
    | '/portfolio/live-action'
    | '/portfolio/vfx-cgi'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/originals'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/portfolio/animation'
    | '/portfolio/live-action'
    | '/portfolio/vfx-cgi'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/originals'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/portfolio_/animation'
    | '/portfolio_/live-action'
    | '/portfolio_/vfx-cgi'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OriginalsRoute: typeof OriginalsRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  PortfolioAnimationRoute: typeof PortfolioAnimationRoute
  PortfolioLiveActionRoute: typeof PortfolioLiveActionRoute
  PortfolioVfxCgiRoute: typeof PortfolioVfxCgiRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals': {
      id: '/originals'
      path: '/originals'
      fullPath: '/originals'
      preLoaderRoute: typeof OriginalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/vfx-cgi': {
      id: '/portfolio_/vfx-cgi'
      path: '/portfolio/vfx-cgi'
      fullPath: '/portfolio/vfx-cgi'
      preLoaderRoute: typeof PortfolioVfxCgiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/live-action': {
      id: '/portfolio_/live-action'
      path: '/portfolio/live-action'
      fullPath: '/portfolio/live-action'
      preLoaderRoute: typeof PortfolioLiveActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/animation': {
      id: '/portfolio_/animation'
      path: '/portfolio/animation'
      fullPath: '/portfolio/animation'
      preLoaderRoute: typeof PortfolioAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OriginalsRoute: OriginalsRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  PortfolioAnimationRoute: PortfolioAnimationRoute,
  PortfolioLiveActionRoute: PortfolioLiveActionRoute,
  PortfolioVfxCgiRoute: PortfolioVfxCgiRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
